In [1]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from emukit.core import ParameterSpace, ContinuousParameter, DiscreteParameter
from emukit.core.initial_designs.random_design import RandomDesign
from emukit.core.initial_designs.latin_design import LatinDesign

In [2]:
def x_normalizer(X, var_array):
    
    def max_min_scaler(x, x_max, x_min):
        return (x-x_min)/(x_max-x_min)
    x_norm = []
    for x in (X):
           x_norm.append([max_min_scaler(x[i], 
                                         max(var_array[i]), 
                                         min(var_array[i])) for i in range(len(x))])
            
    return x_norm

def x_denormalizer(x_norm, var_array):
    
    def max_min_rescaler(x, x_max, x_min):
        return x*(x_max-x_min)+x_min
    x_original = []
    for x in (x_norm):
           x_original.append([max_min_rescaler(x[i], 
                                         max(var_array[i]), 
                                         min(var_array[i])) for i in range(len(x))])
            
    return x_original

def get_closest_value(given_value, array_list):
    absolute_difference_function = lambda list_value : abs(list_value - given_value)
    closest_value = min(array_list, key=absolute_difference_function)
    return closest_value
    
def get_closest_array(suggested_x, var_list):
    modified_array = []
    for x in suggested_x:
        modified_array.append([get_closest_value(x[i], var_list[i]) for i in range(len(x))])
    return np.array(modified_array)

In [4]:
# Define the variable ranges
spinspeed_min, spinspeed_max, spinspeed_step = [500, 5000, 500] ## Unit: rpm
spinspeed_var = np.arange(spinspeed_min, spinspeed_max+spinspeed_step, spinspeed_step) 
spinspeed_num = len(spinspeed_var)

concentration_min, concentration_max, concentration_step = [0.1, 1.5, 0.1] ## Unit: mol/L
concentration_var = np.arange(concentration_min, concentration_max+concentration_step, concentration_step)
concentration_num = len(concentration_var)

annealingtemp_min, annealingtemp_max, annealingtemp_step = [70, 300, 10] # Unit: degC
annealingtemp_var = np.arange(annealingtemp_min, annealingtemp_max+annealingtemp_step, annealingtemp_step)
annealingtemp_num = len(annealingtemp_var)


var_array = [spinspeed_var, concentration_var, 
             annealingtemp_var]
x_labels = ['Spin Speed [rpm]',  
            'Precursor Concentration [mol/L]', 
            'Annealing Temperature [degC]']

random_state = np.random.RandomState(42)
parameter_space = ParameterSpace([ContinuousParameter('x1', 0, 1),
                                 ContinuousParameter('x2', 0, 1),
                                 ContinuousParameter('x3', 0, 1),
                                 ])

# parameter_space = ParameterSpace([DiscreteParameter('x1', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x2', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x3', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x4', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x5', np.linspace(0,1, 51)),
#                                  ])
    

# Generate initial samples with latin hypercube
design = LatinDesign(parameter_space)
x_init = design.get_samples(6)
x_init_original = get_closest_array(x_denormalizer(x_init, var_array),var_array)

df = pd.DataFrame(x_init_original, columns = x_labels)
df_cols = x_labels
df.to_csv("/Users/shengfang/Desktop/TRI/BO_samples_6_latin.csv", index=True)
df

Spin Speed [rpm]  Precursor Concentration [mol/L]  Annealing Temperature [degC]
0                 2500.0   1.1                              130.0
1                 4500.0   1.4                              280.0
2                 1000.0   0.9                              240.0
3                 1500.0   0.2                              170.0
4                 4000.0   0.7                              90.0
5                 3000.0   0.4                              200.0

,Spin Speed [rpm],Precursor Concentration [mol/L],Annealing Temperature [degC]
0,2500.0,1.1,130.0
1,4500.0,1.4,280.0
2,1000.0,0.9,240.0
3,1500.0,0.2,170.0
4,4000.0,0.7,90.0
5,3000.0,0.4,200.0

In [3]:
# Define the variable ranges
spinspeed_min, spinspeed_max, spinspeed_step = [500, 5500, 500] ## Unit: rpm
spinspeed_var = np.arange(spinspeed_min, spinspeed_max+spinspeed_step, spinspeed_step) 
spinspeed_num = len(spinspeed_var)

concentration_min, concentration_max, concentration_step = [0.1, 1.6, 0.1] ## Unit: mol/L
concentration_var = np.arange(concentration_min, concentration_max+concentration_step, concentration_step)
concentration_num = len(concentration_var)

annealingtemp_min, annealingtemp_max, annealingtemp_step = [70, 310, 10] # Unit: degC
annealingtemp_var = np.arange(annealingtemp_min, annealingtemp_max+annealingtemp_step, annealingtemp_step)
annealingtemp_num = len(annealingtemp_var)


var_array = [spinspeed_var, concentration_var, 
             annealingtemp_var]
x_labels = ['Spin Speed [rpm]',  
            'Precursor Concentration [mol/L]', 
            'Annealing Temperature [degC]']

random_state = np.random.RandomState(42)
parameter_space = ParameterSpace([ContinuousParameter('x1', 0, 1),
                                 ContinuousParameter('x2', 0, 1),
                                 ContinuousParameter('x3', 0, 1),
                                 ])

# parameter_space = ParameterSpace([DiscreteParameter('x1', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x2', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x3', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x4', np.linspace(0,1, 51)),
#                                  DiscreteParameter('x5', np.linspace(0,1, 51)),
#                                  ])
    

# Generate initial samples with latin hypercube
design = LatinDesign(parameter_space)
x_init = design.get_samples(6)
x_init_original = get_closest_array(x_denormalizer(x_init, var_array),var_array)

df = pd.DataFrame(x_init_original, columns = x_labels)
df_cols = x_labels
df.to_csv("/Users/shengfang/Desktop/TRI/BO_samples_6_latin_plus.csv", index=True)
df

,Spin Speed [rpm],Precursor Concentration [mol/L],Annealing Temperature [degC]
0,4000.0,1.0,130.0
1,5000.0,1.2,290.0
2,2500.0,0.7,170.0
3,1500.0,0.2,210.0
4,1000.0,1.5,250.0
5,3500.0,0.5,90.0